[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
packages = ["src", "tests"]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = ["uiautomator2", "adbutils"]
ignore_missing_imports = true